### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jmbenedetto** [brandonpittman/OmniFocus#16]
Hi. When I use pip to install de package, I get an error message. I'm using anaconda.

(base) MBPdeBenedetto:~ jmbenedetto$ pip install pyomni==0.1.6.1
Collecting pyomni==0.1.6.1
  Using cached pyomni-0.1.6.1.tar.gz (43 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/jmbenedetto/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/29/7tn4pd3n0_s98m6p6z0cjlvm0000gn/T/pip-install-v1bex1my/pyomni/setup.py'"'"'; __file__='"'"'/private/var/folders/29/7tn4pd3n0_s98m6p6z0cjlvm0000gn/T/pip-install-v1bex1my/pyomni/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/29/7tn4pd3n0_s98m6p6z0cjlvm0000gn/T/pip-pip-egg-info-i1etf175
         cwd: /private/var/folders/29/7tn4pd3n0_s98m6p6z0cjlvm0000gn/T/pip-install-v1bex1my/pyomni/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/29/7tn4pd3n0_s98m6p6z0cjlvm0000gn/T/pip-install-v1bex1my/pyomni/setup.py", line 3, in <module>
        import pyomni
      File "/private/var/folders/29/7tn4pd3n0_s98m6p6z0cjlvm0000gn/T/pip-install-v1bex1my/pyomni/pyomni/__init__.py", line 2, in <module>
        from pyomni.pyomni import PyOmni
      File "/private/var/folders/29/7tn4pd3n0_s98m6p6z0cjlvm0000gn/T/pip-install-v1bex1my/pyomni/pyomni/pyomni.py", line 10, in <module>
        from pyomni.webdav.WebdavClient import CollectionStorer
      File "/private/var/folders/29/7tn4pd3n0_s98m6p6z0cjlvm0000gn/T/pip-install-v1bex1my/pyomni/pyomni/webdav/WebdavClient.py", line 885
        except AuthorizationError, e:
                                 ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jmbenedetto** [comment]
Submitted by mistake
